Getting pp info when a new user is saved.
natsukagami/youmubot pull request #42
Opened 2024-03-15 21:10 UTC by huynd2001

Address #41

2024-03-16 18:54 UTC, natsukagami reviewed
otherwise lgtm

2024-03-16 18:54 UTC, natsukagami commented on youmubot-osu/src/discord/mod.rs
> +
where did this reordering come from?

2024-03-16 18:54 UTC, natsukagami commented on youmubot-osu/src/discord/mod.rs
> +///
just remove the line xd

2024-03-16 18:54 UTC, natsukagami commented on youmubot-osu/src/discord/mod.rs
> +    let std_weight_map_length = calculate_weighted_map_length(&scores, cache, Mode::Std).await?;
maybe do these in parallel: https://docs.rs/futures-util/latest/futures_util/macro.join.html

2024-03-16 23:32 UTC, huynd2001 commented on youmubot-osu/src/discord/mod.rs
> +
Jetbrains' cargo fmt I assume

2024-03-17 16:24 UTC, natsukagami requested changes

2024-03-17 16:24 UTC, natsukagami commented on youmubot-osu/src/discord/mod.rs
> +            .unwrap()
This would panic on API failure, pls handle gracefully 

(return `pp_fut` as Result and handle it or something)

2024-03-17 16:24 UTC, natsukagami commented on youmubot-osu/src/discord/mod.rs
> +            .unwrap();
same

2024-03-17 16:24 UTC, natsukagami commented on youmubot-osu/src/discord/mod.rs
> +            .unwrap()
same

2024-03-17 20:53 UTC, natsukagami requested changes
lol

2024-03-17 20:53 UTC, natsukagami commented on youmubot-osu/src/discord/mod.rs
>                          None
`.pls_ok()` does exactly this

2024-03-17 20:53 UTC, natsukagami commented on youmubot-osu/src/discord/mod.rs
> +                    .next()
```suggestion
                    .and_then(|u| u.pp)
```

2024-03-17 20:54 UTC, huynd2001 commented on youmubot-osu/src/discord/mod.rs
>                          None
TIL

2024-03-17 20:59 UTC, natsukagami approved these changes
If it works feel free to merge

2024-03-17 21:13 UTC, merged